# Required metadata
sonar.projectKey=devops-lab-exam
sonar.projectName=DevOps Lab Exam CI/CD Project
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=.

# Exclude node_modules and UI assets from server-side security checks
sonar.exclusions=node_modules/**, public/**, vercel.json

# Tell SonarQube the language
sonar.language=js

# Encoding of the source code
sonar.sourceEncoding=UTF-8
